### ISSUE TITLE
npm run build fails with cryptic error

### ISSUE THREAD

**Issue by onitake** [shapeblue/primate#36]
When I try to execute a production build with `npm run build`, ` vue-cli-service build` idles for a long time without feedback, then simply exits. `--loglevel verbose` does not help, I only get verbose output from npm but not vue-cli.

This is on CentOS 7, with node.js 10.x installed from Nodesource.
System npm is also coming from Nodesource, but I installed npm@next into /opt/node and I'm running the build with that.

Debug log contains the following:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/opt/node/node_modules/.bin/npm',
1 verbose cli   'run',
1 verbose cli   'build',
1 verbose cli   '--loglevel',
1 verbose cli   'verbose' ]
2 info using npm@6.11.3
3 info using node@v10.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle primate@1.3.0~prebuild: primate@1.3.0
6 info lifecycle primate@1.3.0~build: primate@1.3.0
7 verbose lifecycle primate@1.3.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle primate@1.3.0~build: PATH: /opt/node/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/opt/primate/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin
9 verbose lifecycle primate@1.3.0~build: CWD: /opt/primate
10 silly lifecycle primate@1.3.0~build: Args: [ '-c', 'vue-cli-service build' ]
11 silly lifecycle primate@1.3.0~build: Returned: code: 1  signal: null
12 info lifecycle primate@1.3.0~build: Failed to exec build script
13 verbose stack Error: primate@1.3.0 build: `vue-cli-service build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/opt/node/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/opt/node/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid primate@1.3.0
15 verbose cwd /opt/primate
16 verbose Linux 3.10.0-862.14.4.el7.x86_64
17 verbose argv "/usr/bin/node" "/opt/node/node_modules/.bin/npm" "run" "build" "--loglevel" "verbose"
18 verbose node v10.16.3
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error primate@1.3.0 build: `vue-cli-service build`
22 error Exit status 1
23 error Failed at the primate@1.3.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by rhtyd** [comment]
@onitake probably an env issue, I'm unable to reproduce. You can try in a docker container maybe or newer Linux distro?
My versions:
`npm version
{ primate: '0.1.0',
  npm: '6.10.0',
  ares: '1.14.0',
  cldr: '34.0',
  http_parser: '2.8.0',
  icu: '63.1',
  modules: '64',
  napi: '3',
  nghttp2: '1.36.0',
  node: '10.15.2',
  openssl: '1.1.1b',
  tz: '2018e',
  unicode: '11.0',
  uv: '1.24.1',
  v8: '6.8.275.32-node.12',
  zlib: '1.2.11' }
`

**Comment by onitake** [comment]
Yes... or flimsy npm behaviour. :smile: 

I wasn't to reproduce the issue after running all build steps from the top again.
